apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: client
    app.kubernetes.io/part-of: artifact-uploader
    app.kubernetes.io/managed-by: argocd
  name: artifact-uploader-ui
spec:
  selector:
    app: artifact-uploader-ui
  ports:
  - name: ui-http
    port: 80
  type: LoadBalancer
